name: MooTreeAcordion
author: arieh
category: Interface
tags: [menus, behavioral,utilities]
demo: http://arieh.github.com/MooTreeAcordion/
docs: http://moodocs.net/arieh/mootreeacordion/Tree-Acordion
current: 1.8.2