name: MooTreeAcordion
author: arieh
category: Interface
tags: [menus, behavioral]
#demo: http://tests.arieh.co.il/acord/demo.html
#docs: http://github.com/arieh/MooTreeAcordion/blob/master/Docs/MooTreeAcordion.md
#current: 1.7